# Generated by Django 4.0.6 on 2023-01-26 02:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('codigo_educacion', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre_educacion', models.CharField(max_length=35)),
                ('vigente_educacion', models.BooleanField(default=True)),
                ('fecha_creacion_educacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ini_vig_educacion', models.DateTimeField()),
                ('fecha_fin_vig_educacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educaciones',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('codigo_nivel', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(max_length=20)),
                ('vigente_nivel', models.BooleanField(default=True)),
                ('fecha_creacion_nivel', models.DateTimeField(auto_now_add=True)),
                ('fecha_ini_vig_nivel', models.DateTimeField()),
                ('fecha_fin_vig_nivel', models.DateTimeField(blank=True, null=True)),
                ('educacion_nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.educacion')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('codigo_grado', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=15)),
                ('fecha_creacion_grado', models.DateField(auto_now_add=True)),
                ('fecha_ini_vig_grado', models.DateTimeField()),
                ('fecha_fin_vig_grado', models.DateTimeField(blank=True, null=True)),
                ('vigente_grado', models.BooleanField(default=True)),
                ('nivel_grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.nivel')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo_curso', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('paralelo_curso', models.CharField(max_length=2)),
                ('anno_curso', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1980)])),
                ('vigente_curso', models.BooleanField(default=True)),
                ('fecha_creacion_curso', models.DateTimeField(auto_now_add=True)),
                ('fecha_ini_vig_curso', models.DateTimeField()),
                ('fecha_fin_vig_curso', models.DateTimeField(blank=True, null=True)),
                ('grado_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.grado')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
