# Generated by Django 4.0.6 on 2023-01-29 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_userapoderado_alumno_userapoderado'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['grado_curso', 'codigo_curso', 'vigente_curso'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='educacion',
            options={'ordering': ['codigo_educacion', 'vigente_educacion'], 'verbose_name': 'Educación', 'verbose_name_plural': 'Educaciones'},
        ),
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['nivel_grado', 'codigo_grado', 'vigente_grado'], 'verbose_name': 'Grado', 'verbose_name_plural': 'Grados'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['educacion_nivel', 'codigo_nivel', 'vigente_nivel'], 'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_establecimiento', models.CharField(max_length=150)),
                ('fecha_inauguracion_establecimiento', models.DateField(blank=True, null=True)),
                ('sostenedor_establecimiento', models.CharField(blank=True, max_length=75, null=True)),
                ('tipo_establecimiento', models.CharField(choices=[(1, 'Urbano'), (2, 'Rural')], max_length=15)),
                ('proyecto_educativo', models.FileField(blank=True, null=True, upload_to='')),
                ('direccion_establecimiento', models.CharField(max_length=250)),
                ('is_active_establecimiento', models.BooleanField(default=True)),
                ('comuna_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.comuna')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'ordering': ['comuna_establecimiento', 'nombre_establecimiento'],
            },
        ),
    ]
