# Generated by Django 4.0.6 on 2022-08-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_user_apmat_user_alter_user_celular_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='run_user',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
