# Generated by Django 4.0.6 on 2022-08-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_user_run_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapoderado',
            name='alumno_apoderado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.useralumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userapoderado',
            name='es_sostenedor_apoderado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='run_user',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
