# Generated by Django 4.0.6 on 2022-08-04 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_userapoderado_alumno_apoderado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='foto',
            new_name='foto_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='apmat_user',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='user',
            name='celular_user',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comuna_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.comuna', verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dv_user',
            field=models.CharField(max_length=1, verbose_name='DV'),
        ),
        migrations.AlterField(
            model_name='user',
            name='run_user',
            field=models.PositiveIntegerField(unique=True, verbose_name='RUN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='snombre_user',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Segundo Nombre'),
        ),
    ]
