# Generated by Django 4.0.6 on 2022-08-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_foto_user_foto_user_alter_user_apmat_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapoderado',
            old_name='alumno_apoderado',
            new_name='alumno_userapoderado',
        ),
        migrations.RenameField(
            model_name='userapoderado',
            old_name='es_sostenedor_apoderado',
            new_name='es_sostenedor_userapoderado',
        ),
    ]
