# Generated by Django 4.0.6 on 2022-08-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_useradmin_user_useradmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perfil_base_user',
            field=models.CharField(choices=[('admin', 'Administrador'), ('administrativo', 'Administrativo'), ('alumno', 'Alumno'), ('apoderado', 'Apoderado'), ('auditor', 'Auditor'), ('inspector', 'Inspector'), ('profesor', 'Profesor')], default='admin', max_length=14),
            preserve_default=False,
        ),
    ]
