# Generated by Django 4.0.6 on 2022-08-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_user_perfil_base_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauditor',
            old_name='active_useradmin',
            new_name='active_userauditor',
        ),
        migrations.AlterField(
            model_name='user',
            name='perfil_base_user',
            field=models.CharField(choices=[('admin', 'Administrador'), ('administrativo', 'Administrativo'), ('alumno', 'Alumno'), ('apoderado', 'Apoderado'), ('auditor', 'Auditor'), ('inspector', 'Inspector'), ('profesor', 'Profesor')], max_length=14, verbose_name='Perfil Base'),
        ),
    ]
