# Generated by Django 4.0.6 on 2022-08-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_user_perfil_base_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapoderado',
            name='alumno_userapoderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.useralumno'),
        ),
    ]
